language: java

cache:
  directories:
  - $HOME/.m2

services:
  - xvfb

addons:
  chrome: stable
before_install:
  - sudo apt-get -qq update || echo no sudo apt-get
  - sudo apt-get install -y libgnome2-0
  - sudo apt-get install -y libwebkitgtk-3.0-0 || echo no sudo apt-get
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

#before_script:
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start || echo No X11
#  - sleep 3
install:
  - mvn -pl '!client-android' install -DskipTests=true -Dmaven.javadoc.skip=true -B -ntp
