cache:
  directories:
  - $HOME/.m2

services:
  - xvfb

addons:
  chrome: stable
before_install:
  - sudo apt-get -qq update || echo no sudo apt-get
  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

stages:
  - compile
  - compile1

jobs:
  include:
    - name: job1
      stage: compile
      os:
        - linux
      language: java
      install:
        - mvn install -pl com.dukescript.games.codermasters:puzzlelogic-js, com.dukescript.games.codermasters:puzzlelogic-client, com.dukescript.games.codermasters:puzzlelogic-web, com.dukescript.games.codermasters:puzzlelogic-netbeans -Dmaven.javadoc.skip=true -B -ntp
      script:
        - mvn test -pl com.dukescript.games.codermasters:puzzlelogic-js, -B -ntp
      after_success:
        - mvn coveralls:report -B
      workspaces:
        create:
          name: ws1
          paths:
            - $HOME/.m2
    - name: job2
      stage: compile1
      language: android
      depends_on: job1
      android:
        components:
          - extra-google-m2repository
          - extra-android-m2repository
      workspaces:
        use: ws1
      install:
        - mvn install -pl com.dukescript.games.codermasters:puzzlelogic-android,com.dukescript.games.codermasters:puzzlelogic-pom -DskipTests=true -Dmaven.javadoc.skip=true -B -ntp
      script:
        - mvn test -pl com.dukescript.games.codermasters:puzzlelogic-android org.jacoco:jacoco-maven-plugin:0.8.2:report -B -ntp
